### PR TITLE
feat: add Build CI

### PR DESCRIPTION
**Pull request by GmBodhi**

### CODE REVIEW

**Comment by GmBodhi** [comment]
:sus:

**Comment by DolphinIQ** [comment]
Hi, what's this for?

**Comment by GmBodhi** [comment]
> Hi, what's this for?

You don't have to run `npm run build` before you commit, it'll do it and commit the changes automatically.

**Comment by DolphinIQ** [comment]
`npm run build` is a continuous rollup `watch` build I use for development anyway. It takes less than 2 seconds and builds after any change to `src/`, meaning it will always be built before the commit. What's the point of building again pre-commit? 🤔

**Comment by GmBodhi** [comment]
Hmm. Okay. Then there is no reason for this to exist

**Comment by GmBodhi** [comment]
image

**Comment by DolphinIQ** [comment]
Oh well, thanks for the initiative. Perhaps something like this will be useful later on in the future. Closing for now

**Pull request closed without merging**
